name = "wt-phishing-test"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "RANKING_KV"
id = "140a8415d8bf4c72a337b802f30456a8"
